### ISSUE TITLE
Add parent terms to info box

### ISSUE THREAD

**Issue by veitveit** [IFB-ElixirFr/edam-browser#35]
Particularly for formats, where the terms are children of both file type family (e.g. "XML") and category ("Sequence alignment"), it would come handy to see them in the box with the details about the term.

**Comment by bryan-brancotte** [comment]
Hi, I don't understand fully your suggestion. Could you provide us an element (ideally with its URI) being a child of "XML" and "Sequence alignment" ?

Did you mean [operation_0292](https://ifb-elixirfr.github.io/edam-browser/#operation_0292) or [data_0863](https://ifb-elixirfr.github.io/edam-browser/#data_0863) for "category" Sequence alignment

**Comment by bryan-brancotte** [comment]
OK, i understand now, the other parent is also selected in the tree visualisation but due to the number of siblings, and the initial zoom, "Protein interaction format" is way upper in the tree rendering (see hereafter) and not seen
![capture d ecran de 2018-11-14 17-03-31](https://user-images.githubusercontent.com/11556772/48494990-54e1ef00-e82f-11e8-8140-b37e62c02baf.png)

We indeed could add it to the detail panel on the right.

**Comment by veitveit** [comment]
Oh, I didn't see that! Would still be nice to have :-)

Thanks

**Comment by bryan-brancotte** [comment]
done :-)
