### ISSUE TITLE
Double parent for entity

### ISSUE THREAD

**Issue by aizquier** [IFB-ElixirFr/edam-browser#38]
Hello!
Currently at Montreal University we are developing an ontology for a catalogue of scientific equipment, and your browser seems very useful for the project. Following the schema you propose in https://github.com/IFB-ElixirFr/edam-browser/blob/master/ontology.schema.json we see that an entity can have only a parent, however checking the schema of the EDAM ontology it supports the notion of multiple parents (which are rendered by the browser). As we need to support entities with multiple parents, we are interested how do you feed teh EDAM schema into the browser, so we could adapt our data as well. Thank you!!

**Comment by bryan-brancotte** [comment]
Hello !

Thanks for your interest in the browser.

## Handling multiple parent

Indeed EDAM supports the notion of multiple parents, during the conversion from owl to json (thanks to https://github.com/edamontology/edam2json) a node with multiple parent is duplicated to be the child of each parent. Then in the browser when the user click on a node, instead of expanding the current node, we ask the tree to expand all node the that have the same id as the current node.

## Edam browser is not only for EDAM !

The browser can be used it with any ontology as long as you respect the schema, and the ontology can fit into memory.

### A simple ontology in json 
https://github.com/IFB-ElixirFr/edam-browser/blob/master/media/regular.example.json
https://raw.githubusercontent.com/IFB-ElixirFr/edam-browser/master/media/regular.example.json

### And browsing this simple ontology
https://ifb-elixirfr.github.io/edam-browser/?url=https%3A%2F%2Fifb-elixirfr.github.io%2Fedam-browser%2Fmedia%2Fregular.example.json&identifier_accessor=d.id&text_accessor=d.text#p9&custom_url
